/* 本文件由 gen_default_text.py 自动生成，请勿手工修改。
 * 来源：Note.txt（换行已规范为 \n）。
 */
#pragma once

#define DEFAULT_TEXT_LEN 40099

static const char DEFAULT_TEXT[] =
    "#include <string.h>\n\n#include \"freertos/FreeRTOS.h\"\n#include \"freertos/task.h\"\n#include \"fr"
    "eertos/event_groups.h\"\n\n#include \"esp_random.h\"\n#include \"esp_log.h\"\n#include \"esp_err.h\""
    "\n#include \"esp_timer.h\"\n\n#include \"ble_hid.h\"\n#include \"led_status.h\"\n#include \"action_e"
    "ngine.h\"\n\nstatic const char *TAG = \"ACTION_ENGINE\";\n\n#include \"config_store.h\"\n#include \""
    "wifi_manager.h\"\n\n#define RUN_BIT        (1 << 0)    \n#define STOP_BIT       (1 << 1)    \n#defin"
    "e DISCONNECT_BIT (1 << 2)    \n\n#include <time.h>\ntypedef act_id_t action_id_t;\n\nstatic EventGro"
    "upHandle_t s_action_evt = NULL;\nstatic bool              s_task_created = false;\n\nstatic int64_t "
    "s_run_deadline_us = 0;\n \nstatic int64_t s_sched_stop_deadline_us = 0;\n \nstatic int32_t s_runtime"
    "_minutes = 0;\n \nstatic int32_t s_last_blink_minute = -1;\n\nstatic void reset_runtime(void);\n \ns"
    "tatic void log_remaining_time(void);\n \nstatic void led_control_task(void *arg);\n \nstatic void le"
    "d_notify_blink_once(void);\n \nstatic void exec_action_by_id(uint8_t action_id);\n \nstatic void sch"
    "eduler_task(void *arg);\n\nstatic run_mode_t       s_run_mode   = RUN_MODE_RANDOM;\nstatic action_we"
    "ights_t s_weights = {                  \n    ACT_W_DRAG, ACT_W_CLICK, ACT_W_WHEEL, ACT_W_ARROW, ACT_"
    "W_REST, ACT_W_MOVE, ACT_W_WORD,\n};\nstatic action_seq_t     s_sequence;                    \nstatic"
    " uint8_t          s_seq_cursor = 0;              \nstatic uint8_t          s_seq_shuffle[ACT_SEQ_MAX"
    "];    \nstatic uint8_t          s_seq_shuffle_len = 0;         \nstatic bool             s_seq_once_"
    "stop = false;       \n\nstatic void reset_runtime(void)\n{\n    s_run_deadline_us = 0;\n    s_sched_"
    "stop_deadline_us = 0;\n    s_runtime_minutes = 0;\n    s_last_blink_minute = -1;\n}\n\n#define LED_B"
    "LINK_ON_MS         80       \n#define LED_FREQ_PER_1MIN_MS    50       \n#define LED_FREQ_MAX_MS    "
    "     2000     \n#define LED_BLINK_ONCE_MS       200      \n#define LED_BLINK_ONCE_GAP_MS   200      "
    "\nstatic EventGroupHandle_t s_led_evt = NULL;\n#define LED_BLINK_ONCE_BIT  (1 << 0)\n\nstatic bool  "
    "   s_prev_synced = false;\nstatic int64_t  s_timeset_guard_until = 0;    \n#define TIMESET_GUARD_US "
    " (10ULL * 1000 * 1000)    \n\nstatic int64_t get_remaining_us(void)\n{\n    int64_t now = esp_timer_"
    "get_time();\n    int64_t eff = 0;\n    if (s_run_deadline_us != 0 && (eff == 0 || s_run_deadline_us "
    "< eff)) {\n        eff = s_run_deadline_us;\n    }\n    if (s_sched_stop_deadline_us != 0 && (eff =="
    " 0 || s_sched_stop_deadline_us < eff)) {\n        eff = s_sched_stop_deadline_us;\n    }\n    if (ef"
    "f == 0) {\n        return 0;\n    }\n    int64_t remain = eff - now;\n    return remain > 0 ? remain"
    " : 0;\n}\n\nstatic void log_remaining_time(void)\n{\n    if ((xEventGroupGetBits(s_action_evt) & RUN"
    "_BIT) == 0) {\n        return;\n    }\n    if (s_run_deadline_us == 0 && s_sched_stop_deadline_us =="
    " 0) {\n        return;    \n    }\n    int64_t remain_us = get_remaining_us();\n    int32_t remain_m"
    "in = (int32_t)(remain_us / 1000000LL / 60);\n    int32_t remain_sec = (int32_t)((remain_us / 1000000"
    "LL) % 60);\n    ESP_LOGI(TAG, \"[SOTQ\302\267SCbtpf] %ld z %ld w\",\n             (long)remain_min, "
    "(long)remain_sec);\n}\n\nstatic void led_notify_blink_once(void)\n{\n    if (s_led_evt != NULL) {\n "
    "       xEventGroupSetBits(s_led_evt, LED_BLINK_ONCE_BIT);\n    }\n}\n\nstatic int32_t s_cur_x = 0;\n"
    "static int32_t s_cur_y = 0;\n\nstatic int32_t clamp_x(int32_t x)\n{\n    if (x > MOUSE_POS_EFF_X) re"
    "turn MOUSE_POS_EFF_X;\n    if (x < -MOUSE_POS_EFF_X) return -MOUSE_POS_EFF_X;\n    return x;\n}\nsta"
    "tic int32_t clamp_y(int32_t y)\n{\n    if (y > MOUSE_POS_EFF_Y) return MOUSE_POS_EFF_Y;\n    if (y <"
    " -MOUSE_POS_EFF_Y) return -MOUSE_POS_EFF_Y;\n    return y;\n}\n\nstatic int rand_range(int min, int "
    "max)\n{\n    if (max <= min) {\n        return min;\n    }\n    uint32_t r = esp_random();\n    retu"
    "rn (int)(r % (uint32_t)(max - min + 1)) + min;\n}\n\nstatic const action_timing_t *ae_timing(void)\n"
    "{\n    return &config_store_get()->timing;\n}\n\nstatic bool action_delay_ms(uint32_t ms)\n{\n    if"
    " (ms == 0) {\n        return true;\n    }\n    EventBits_t bits = xEventGroupWaitBits(\n        s_ac"
    "tion_evt,\n        STOP_BIT | DISCONNECT_BIT,\n        pdFALSE,             \n        pdFALSE,      "
    "       \n        pdMS_TO_TICKS(ms));\n    return (bits & (STOP_BIT | DISCONNECT_BIT)) == 0;\n}\n\nst"
    "atic bool mouse_move_relative_chunk(int32_t total_dx, int32_t total_dy, uint8_t chunk, uint32_t step"
    "_ms, uint8_t buttons)\n{\n    if (chunk < 1) chunk = 1;\n    if (chunk > 127) chunk = 127;    \n    "
    "bool neg_x = total_dx < 0;\n    bool neg_y = total_dy < 0;\n    int32_t rem_x = total_dx < 0 ? -tota"
    "l_dx : total_dx;\n    int32_t rem_y = total_dy < 0 ? -total_dy : total_dy;\n\n    while (rem_x > 0 |"
    "| rem_y > 0) {\n        int32_t cx = (rem_x > chunk) ? chunk : rem_x;\n        int32_t cy = (rem_y >"
    " chunk) ? chunk : rem_y;\n        int8_t dx = (int8_t)(neg_x ? -cx : cx);\n        int8_t dy = (int8"
    "_t)(neg_y ? -cy : cy);\n\n        esp_err_t err = ble_hid_send_mouse_full_blocking(dx, dy, 0, button"
    "s);\n        if (err != ESP_OK) {\n            ESP_LOGW(TAG, \"DfpaehbR: %s\", esp_err_to_name(err))"
    ";\n        }\n\n        rem_x -= cx;\n        rem_y -= cy;\n\n        if (rem_x > 0 || rem_y > 0) {"
    "\n            if (!action_delay_ms(step_ms)) {\n                return false;\n            }\n      "
    "  }\n    }\n    return true;\n}\n\nstatic bool mouse_move_relative(int32_t total_dx, int32_t total_d"
    "y, uint32_t step_ms, uint8_t buttons)\n{\n    return mouse_move_relative_chunk(total_dx, total_dy, A"
    "CTION_MOVE_CHUNK_MAX, step_ms, buttons);\n}\n\nstatic bool mouse_move_random(int32_t dist_min, int32"
    "_t dist_max,\n                               uint8_t step_min, uint8_t step_max,\n                  "
    "             uint32_t step_ms, uint8_t buttons)\n{\n    int32_t dist = rand_range(dist_min, dist_max"
    ");\n    if (dist <= 0) {\n        return true;\n    }\n     \n    int32_t ang = rand_range(0, 7);\n "
    "   static const int32_t dir_x[8] = { 1, 1, 0, -1, -1, -1, 0, 1};\n    static const int32_t dir_y[8] "
    "= { 0, 1, 1, 1, 0, -1, -1, -1};\n    int32_t dx = dir_x[ang];\n    int32_t dy = dir_y[ang];\n     \n"
    "    int32_t target_x = clamp_x(s_cur_x + dx * dist);\n    int32_t target_y = clamp_y(s_cur_y + dy * "
    "dist);\n    int32_t total_dx = target_x - s_cur_x;\n    int32_t total_dy = target_y - s_cur_y;\n    "
    "if (total_dx == 0 && total_dy == 0) {\n        return true;    \n    }\n    uint8_t chunk = (uint8_t"
    ")rand_range(step_min, step_max);\n    if (chunk < 1) chunk = 1;\n    if (chunk > ACTION_MOVE_CHUNK_M"
    "AX) chunk = ACTION_MOVE_CHUNK_MAX;\n    bool ok = mouse_move_relative_chunk(total_dx, total_dy, chun"
    "k, step_ms, buttons);\n    if (ok) {\n        s_cur_x = target_x;\n        s_cur_y = target_y;\n    "
    "}\n    return ok;\n}\n\nstatic void mouse_wheel(int8_t delta)\n{\n    if (delta == 0) {\n        ret"
    "urn;\n    }\n    int8_t sign = (delta > 0) ? 1 : -1;\n    int8_t rem = (int8_t)(delta > 0 ? delta : "
    "-delta);\n    while (rem > 0) {\n         \n        int8_t step = rem;\n        ble_hid_send_mouse_f"
    "ull_blocking(0, 0, (int8_t)(sign * step), 0);\n        rem -= step;\n    }\n}\n\nstatic void mouse_b"
    "utton(uint8_t buttons)\n{\n    ble_hid_send_mouse_full_blocking(0, 0, 0, buttons);\n}\n\nstatic void"
    " action_release_all(void)\n{\n     \n    ble_hid_send_mouse_full_blocking(0, 0, 0, 0);\n     \n    b"
    "le_hid_send_key(HID_KEY_ARROW_UP,    false);\n    ble_hid_send_key(HID_KEY_ARROW_DOWN,  false);\n   "
    " ble_hid_send_key(HID_KEY_ARROW_LEFT,  false);\n    ble_hid_send_key(HID_KEY_ARROW_RIGHT, false);\n}"
    "\n\ntypedef enum {\n    CORNER_TOP_RIGHT = 0,    \n    CORNER_TOP_LEFT,         \n    CORNER_BOTTOM_"
    "RIGHT,     \n    CORNER_BOTTOM_LEFT,      \n} mouse_corner_t;\n\nstatic const struct {\n    int8_t d"
    "x;\n    int8_t dy;\n} s_corner_dir[4] = {\n    [CORNER_TOP_RIGHT]    = { 127, -127},\n    [CORNER_TO"
    "P_LEFT]     = {-127, -127},\n    [CORNER_BOTTOM_RIGHT] = { 127,  127},\n    [CORNER_BOTTOM_LEFT]  = "
    "{-127,  127},\n};\n\nstatic bool action_mouse_home(void)\n{\n    mouse_corner_t corner = (mouse_corn"
    "er_t)(MOUSE_HOME_CORNER);\n    if (corner > CORNER_BOTTOM_LEFT) {\n        corner = CORNER_TOP_RIGHT"
    ";\n    }\n    int sign_x = (s_corner_dir[corner].dx > 0) ? 1 : -1;\n    int sign_y = (s_corner_dir[c"
    "orner].dy > 0) ? 1 : -1;\n\n    int32_t push = (int32_t)MOUSE_HOME_PUSH_PX;\n    int32_t back_x = (i"
    "nt32_t)MOUSE_HOME_BACK_X;\n    int32_t back_y = (int32_t)MOUSE_HOME_BACK_Y;\n\n    ESP_LOGI(TAG, \"V"
    "J: J=%d sign=(%d,%d) PUSH=%d BACK_X=%d BACK_Y=%d\",\n             (int)corner, (int)sign_x, (int)sig"
    "n_y, (int)push, (int)back_x, (int)back_y);\n\n    if (!mouse_move_relative(sign_x * push, sign_y * p"
    "ush, ACTION_HOME_STEP_MS, 0)) {\n        return false;\n    }\n\n    if (!mouse_move_relative(-sign_"
    "x * back_x, -sign_y * back_y, ACTION_MOVE_STEP_MS, 0)) {\n        return false;\n    }\n\n    s_cur_"
    "x = 0;\n    s_cur_y = 0;\n    return true;\n}\n\nstatic void act_drag(void)\n{\n    const action_tim"
    "ing_t *T = ae_timing();\n    int repeat = rand_range(T->drag_repeat_min, T->drag_repeat_max);\n    E"
    "SP_LOGI(TAG, \"[FY] zr jd=%d p\", repeat);\n\n    mouse_button(HID_MOUSE_BTN_LEFT);\n\n    for (int "
    "i = 0; i < repeat; i++) {\n         \n        if (!mouse_move_random(T->drag_distance_min, T->drag_d"
    "istance_max,\n                                T->drag_step_min, T->drag_step_max,\n                 "
    "               ACTION_MOVE_STEP_MS, HID_MOUSE_BTN_LEFT)) {\n            goto exit_release;\n        "
    "}\n        int interval = rand_range(T->drag_interval_min, T->drag_interval_max);\n        if (!acti"
    "on_delay_ms(interval)) {\n            goto exit_release;\n        }\n    }\n\n    mouse_button(0);\n"
    "     \n    if (!action_mouse_home()) {\n        goto exit_release;\n    }\n     \n    action_delay_m"
    "s(rand_range(T->drag_end_delay_min, T->drag_end_delay_max));\n\nexit_release:\n    action_release_al"
    "l();\n}\n\nstatic void act_click(void)\n{\n    const action_timing_t *T = ae_timing();\n    int repe"
    "at = rand_range(T->click_repeat_min, T->click_repeat_max);\n    ESP_LOGI(TAG, \"[yo] LS NH=%d x\", r"
    "epeat);\n\n    for (int i = 0; i < repeat; i++) {\n         \n        if (!mouse_move_random(T->clic"
    "k_distance_min, T->click_distance_max,\n                               T->click_step_min, T->click_s"
    "tep_max,\n                               ACTION_MOVE_STEP_MS, 0)) {\n            goto exit_release;"
    "\n        }\n         \n        mouse_button(HID_MOUSE_BTN_LEFT);\n        if (!action_delay_ms(rand"
    "_range(T->click_hold_min, T->click_hold_max))) {\n            goto exit_release;\n        }\n       "
    " mouse_button(0);\n        int interval = rand_range(T->click_interval_min, T->click_interval_max);"
    "\n        if (!action_delay_ms(interval)) {\n            goto exit_release;\n        }\n    }\n\n   "
    " if (!action_mouse_home()) {\n        goto exit_release;\n    }\n    action_delay_ms(rand_range(T->c"
    "lick_end_delay_min, T->click_end_delay_max));\n\nexit_release:\n    action_release_all();\n}\n\nstat"
    "ic void act_wheel(void)\n{\n    const action_timing_t *T = ae_timing();\n    int repeat = rand_range"
    "(T->wheel_repeat_min, T->wheel_repeat_max);\n    ESP_LOGI(TAG, \"[pR] qR(yn+MUQt) mD=%d S\", repeat)"
    ";\n\n    int wheel_sum = 0;\n\n    for (int i = 0; i < repeat; i++) {\n         \n        mouse_move"
    "_random(T->wheel_distance_min, T->wheel_distance_max,\n                          T->wheel_step_min, "
    "T->wheel_step_max,\n                          ACTION_MOVE_STEP_MS, 0);\n\n        int dir  = (esp_ra"
    "ndom() & 0x1) ? 1 : -1;\n        int tick = rand_range(T->wheel_tick_min, T->wheel_tick_max);\n     "
    "   int delta = dir * tick;\n        wheel_sum += delta;\n        mouse_wheel((int8_t)delta);\n\n    "
    "    if (!action_delay_ms(rand_range(T->wheel_interval_min, T->wheel_interval_max))) {\n            g"
    "oto exit_release;\n        }\n    }\n\n    if (wheel_sum != 0) {\n        mouse_wheel((int8_t)(-whee"
    "l_sum));\n    }\n\n    if (!action_mouse_home()) {\n        goto exit_release;\n    }\n    action_de"
    "lay_ms(rand_range(T->wheel_end_delay_min, T->wheel_end_delay_max));\n\nexit_release:\n    action_rel"
    "ease_all();\n}\n\nstatic void act_arrow_keys(void)\n{\n    const action_timing_t *T = ae_timing();\n"
    "    int repeat = rand_range(T->arrow_repeat_min, T->arrow_repeat_max);\n    ESP_LOGI(TAG, \"[fz] hre"
    " QV=%d L\", repeat);\n\n    const uint8_t arrows[4] = {\n        HID_KEY_ARROW_UP, HID_KEY_ARROW_DOW"
    "N,\n        HID_KEY_ARROW_LEFT, HID_KEY_ARROW_RIGHT,\n    };\n\n    for (int i = 0; i < repeat; i++)"
    " {\n        uint8_t k = arrows[rand_range(0, 3)];\n        ble_hid_send_key(k, true);\n        if (!"
    "action_delay_ms(10)) {\n            goto exit_release;\n        }\n        ble_hid_send_key(k, false"
    ");\n        if (!action_delay_ms(rand_range(T->arrow_interval_min, T->arrow_interval_max))) {\n     "
    "       goto exit_release;\n        }\n    }\n\n    action_delay_ms(rand_range(T->arrow_end_delay_min"
    ", T->arrow_end_delay_max));\n\nexit_release:\n    action_release_all();\n}\n\nstatic void act_word(v"
    "oid)\n{\n    const action_timing_t *T = ae_timing();\n    const config_t *cfg = config_store_get();"
    "\n    if (cfg == NULL) {\n        return;\n    }\n    const char *list = cfg->word.list;\n    if (li"
    "st[0] == '\\0') {\n         \n        list = config_store_default_word_list();\n        ESP_LOGW(TAG"
    ", \"[qr] Ea\357\274\232oFkAQ\357\274\214JqFErpuRRC\");\n    }\n\n    int word_cnt = 0;\n    bool in_"
    "word = false;\n    for (const char *p = list; *p; ++p) {\n        if (*p == ' ' || *p == '\\t' || *p"
    " == '\\n' || *p == '\\r') {\n            in_word = false;\n        } else if (!in_word) {\n         "
    "   in_word = true;\n            word_cnt++;\n        }\n    }\n    if (word_cnt == 0) {\n        ESP"
    "_LOGW(TAG, \"[RF] Dt\357\274\232anMLC\357\274\214TK\");\n        return;\n    }\n    ESP_LOGI(TAG, "
    "\"[ZK] Ml cSUF=%d\", word_cnt);\n\n    int repeat = rand_range(T->word_repeat_min, T->word_repeat_ma"
    "x);\n    if (repeat < 1) repeat = 1;\n\n    for (int r = 0; r < repeat; r++) {\n         \n        i"
    "nt pick = rand_range(0, word_cnt - 1);\n        const char *p = list;\n        int idx = 0;\n       "
    " in_word = false;\n        const char *wstart = NULL;\n        int wlen = 0;\n        while (*p) {\n"
    "            if (*p == ' ' || *p == '\\t' || *p == '\\n' || *p == '\\r') {\n                if (in_wo"
    "rd) {  \n                    if (idx == pick) { wlen = (int)(p - wstart); break; }\n                "
    "    in_word = false;\n                }\n            } else {\n                if (!in_word) { in_wo"
    "rd = true; wstart = p; if (idx == pick) {   } idx++; }\n                else if (idx - 1 == pick) { "
    "  }\n            }\n            p++;\n        }\n         \n        if (wlen == 0 && in_word && idx "
    "- 1 == pick) {\n            wlen = (int)(p - wstart);\n        }\n        if (wlen <= 0 || wstart =="
    " NULL) {\n            continue;\n        }\n\n        for (int i = 0; i < wlen; i++) {\n            "
    "char buf[2] = { wstart[i], '\\0' };\n            ble_hid_send_string(buf);\n            if (!action_"
    "delay_ms(rand_range(T->word_char_delay_min, T->word_char_delay_max))) {\n                goto exit_r"
    "elease;\n            }\n        }\n         \n        ble_hid_send_string(\" \");\n        if (!acti"
    "on_delay_ms(rand_range(T->word_space_delay_min, T->word_space_delay_max))) {\n            goto exit_"
    "release;\n        }\n    }\n\n    action_delay_ms(rand_range(T->word_end_delay_min, T->word_end_dela"
    "y_max));\n\nexit_release:\n    action_release_all();\n}\nstatic void act_rest(void)\n{\n    const ac"
    "tion_timing_t *T = ae_timing();\n    int delay = rand_range(T->rest_delay_min, T->rest_delay_max);\n"
    "    ESP_LOGI(TAG, \"[ur] nb %d ms\", delay);\n    action_delay_ms((uint32_t)delay);\n    action_rele"
    "ase_all();\n}\n\nstatic void act_move(void)\n{\n    const action_timing_t *T = ae_timing();\n    int"
    " repeat = rand_range(T->move_repeat_min, T->move_repeat_max);\n    int step   = rand_range(T->move_s"
    "tep_min, T->move_step_max);\n    if (step < 1) step = 1;\n    if (step > 127) step = 127;\n    ESP_L"
    "OGI(TAG, \"[jr] Fq UG=%d qm=%d\", repeat, step);\n\n    for (int i = 0; i < repeat; i++) {\n        "
    "int dist = rand_range(T->move_distance_min, T->move_distance_max);\n        if (dist < 1) dist = 1;"
    "\n         \n        uint8_t dir = (uint8_t)(esp_random() & 0x7);\n        int32_t dx = 0, dy = 0;\n"
    "        switch (dir) {\n        case 0: dx =  dist; break;\n        case 1: dx = -dist; break;\n    "
    "    case 2: dy = -dist; break;\n        case 3: dy =  dist; break;\n        case 4: dx =  dist; dy ="
    " -dist; break;\n        case 5: dx =  dist; dy =  dist; break;\n        case 6: dx = -dist; dy = -di"
    "st; break;\n        default:dx = -dist; dy =  dist; break;\n        }\n         \n        int32_t tx"
    " = clamp_x(s_cur_x + dx);\n        int32_t ty = clamp_y(s_cur_y + dy);\n        if (tx == s_cur_x &&"
    " ty == s_cur_y) {\n             \n            int32_t span_x = MOUSE_POS_EFF_X * 2;\n            int"
    "32_t span_y = MOUSE_POS_EFF_Y * 2;\n            tx = (int32_t)(esp_random() % (uint32_t)(span_x + 1)"
    ") - MOUSE_POS_EFF_X;\n            ty = (int32_t)(esp_random() % (uint32_t)(span_y + 1)) - MOUSE_POS_"
    "EFF_Y;\n        }\n         \n        if (!mouse_move_relative_chunk(tx - s_cur_x, ty - s_cur_y, (ui"
    "nt8_t)step, ACTION_MOVE_STEP_MS, 0)) {\n            goto exit_release;\n        }\n        s_cur_x ="
    " tx;\n        s_cur_y = ty;\n        int interval = rand_range(T->move_interval_min, T->move_interva"
    "l_max);\n        if (!action_delay_ms(interval)) {\n            goto exit_release;\n        }\n    }"
    "\n\n    if (!action_mouse_home()) {\n        goto exit_release;\n    }\n    action_delay_ms(rand_ran"
    "ge(T->move_end_delay_min, T->move_end_delay_max));\n\nexit_release:\n    action_release_all();\n}\n"
    "\nstatic action_id_t pick_action(void)\n{\n    int weights[ACT_COUNT] = {\n        s_weights.drag, s"
    "_weights.click, s_weights.wheel,\n        s_weights.arrow, s_weights.rest, s_weights.move, s_weights"
    ".word,\n    };\n    int total = 0;\n    for (int i = 0; i < ACT_COUNT; i++) {\n        if (weights[i"
    "] < 0) {\n            weights[i] = 0;    \n        }\n        total += weights[i];\n    }\n    if (t"
    "otal <= 0) {\n        return ACT_REST;       \n    }\n    int r = (int)(esp_random() % (uint32_t)tot"
    "al);\n    int acc = 0;\n    for (int i = 0; i < ACT_COUNT; i++) {\n        acc += weights[i];\n     "
    "   if (r < acc) {\n            return (action_id_t)i;\n        }\n    }\n    return ACT_REST;\n}\n\n"
    "static void exec_action_by_id(uint8_t action_id)\n{\n    switch (action_id) {\n    case ACT_DRAG:   "
    "act_drag();       break;\n    case ACT_CLICK:  act_click();      break;\n    case ACT_WHEEL:  act_wh"
    "eel();      break;\n    case ACT_ARROW:  act_arrow_keys(); break;\n    case ACT_REST:   act_rest(); "
    "      break;\n    case ACT_MOVE:   act_move();       break;\n    case ACT_WORD:   act_word();       "
    "break;\n    default:         act_rest();       break;\n    }\n}\n\nstatic void build_shuffle_order(c"
    "onst action_seq_t *seq)\n{\n    uint8_t tmp[ACT_SEQ_MAX];\n    uint8_t n = (seq->count > ACT_SEQ_MAX"
    ") ? ACT_SEQ_MAX : seq->count;\n    for (uint8_t i = 0; i < n; i++) {\n        tmp[i] = seq->actions["
    "i];\n    }\n     \n    for (uint8_t i = n; i > 1; i--) {\n        uint8_t j = (uint8_t)(esp_random()"
    " % i);\n        uint8_t t = tmp[i - 1];\n        tmp[i - 1] = tmp[j];\n        tmp[j] = t;\n    }\n "
    "   memcpy(s_seq_shuffle, tmp, n);\n    s_seq_shuffle_len = n;\n}\n\nstatic uint8_t seq_action_at(uin"
    "t8_t idx)\n{\n    uint8_t n = (s_sequence.count > ACT_SEQ_MAX) ? ACT_SEQ_MAX : s_sequence.count;\n  "
    "  if (n == 0) {\n        return ACT_REST;\n    }\n    if (idx >= n) {\n        idx = (uint8_t)(idx %"
    " n);\n    }\n    if (s_sequence.cycle == CYCLE_SHUFFLE && s_seq_shuffle_len > 0) {\n        return s"
    "_seq_shuffle[idx];\n    }\n    return s_sequence.actions[idx];\n}\n\nvoid action_engine_trigger_sequ"
    "ence_once(void)\n{\n    uint8_t n = (s_sequence.count > ACT_SEQ_MAX) ? ACT_SEQ_MAX : s_sequence.coun"
    "t;\n    if (n == 0) {\n        return;\n    }\n    if (!ble_hid_is_connected()) {\n        ESP_LOGW("
    "TAG, \"yEWF\357\274\232TnhPF\357\274\214sZ\");\n        return;\n    }\n    if (s_sequence.cycle == "
    "CYCLE_SHUFFLE) {\n        build_shuffle_order(&s_sequence);\n    }\n    for (uint8_t i = 0; i < n; i"
    "++) {\n        if (!ble_hid_is_connected()) {\n            break;    \n        }\n        exec_actio"
    "n_by_id(seq_action_at(i));\n    }\n}\n\nvoid action_engine_run_single(uint8_t action_id)\n{\n    if "
    "(!ble_hid_is_connected()) {\n        ESP_LOGW(TAG, \"rHeyv\357\274\232yVaMH\357\274\214YD action=%d"
    "\", action_id);\n        return;\n    }\n    ESP_LOGI(TAG, \"[MPzIP] Pp action_id=%d\", action_id);"
    "\n    exec_action_by_id(action_id);\n}\n\nstatic void action_engine_task(void *arg)\n{\n    (void)ar"
    "g;\n\n    ESP_LOGI(TAG, \"mKhxuiDHX\357\274\214mq KEY2 cY...\");\n\n    while (1) {\n        EventBi"
    "ts_t bits = xEventGroupWaitBits(\n            s_action_evt,\n            RUN_BIT | STOP_BIT | DISCON"
    "NECT_BIT,\n            pdFALSE, pdFALSE, portMAX_DELAY);\n\n        if ((bits & RUN_BIT) == 0) {\n  "
    "           \n            action_release_all();\n            xEventGroupClearBits(s_action_evt, STOP_"
    "BIT | DISCONNECT_BIT);\n            continue;\n        }\n\n        if (s_run_deadline_us != 0 &&\n "
    "           esp_timer_get_time() >= s_run_deadline_us) {\n            ESP_LOGI(TAG, \">>> tgcf\357"
    "\274\210%ld Yh\357\274\211nkf\357\274\214aDZb <<<\",\n                     (long)s_runtime_minutes);"
    "\n            reset_runtime();\n            xEventGroupClearBits(s_action_evt, RUN_BIT);\n          "
    "  xEventGroupSetBits(s_action_evt, STOP_BIT);\n            action_release_all();\n            xEvent"
    "GroupClearBits(s_action_evt, STOP_BIT | DISCONNECT_BIT);\n            continue;\n        }\n\n      "
    "  if (!ble_hid_is_connected()) {\n            if (!action_delay_ms(500)) {\n                action_r"
    "elease_all();\n            }\n            continue;\n        }\n\n        if (!action_mouse_home()) "
    "{\n            action_release_all();\n            continue;\n        }\n\n        if (s_run_mode == "
    "RUN_MODE_SEQUENCE) {\n            uint8_t n = (s_sequence.count > ACT_SEQ_MAX) ? ACT_SEQ_MAX : s_seq"
    "uence.count;\n            if (n == 0) {\n                exec_action_by_id(ACT_REST);    \n         "
    "   } else {\n                uint8_t act = seq_action_at(s_seq_cursor);\n                exec_action"
    "_by_id(act);\n                s_seq_cursor++;\n                if (s_seq_cursor >= n) {\n           "
    "          \n                    s_seq_cursor = 0;\n                    if (s_sequence.cycle == CYCLE"
    "_SHUFFLE) {\n                        build_shuffle_order(&s_sequence);\n                    } else i"
    "f (s_sequence.cycle == CYCLE_ONCE) {\n                         \n                        ESP_LOGI(TA"
    "G, \">>> kdSx\357\274\232ftaFwVz\357\274\214OqaZ <<<\");\n                        s_seq_once_stop = "
    "true;\n                        xEventGroupClearBits(s_action_evt, RUN_BIT);\n                       "
    " xEventGroupSetBits(s_action_evt, STOP_BIT);\n                        action_release_all();\n       "
    "                 xEventGroupClearBits(s_action_evt, STOP_BIT | DISCONNECT_BIT);\n                   "
    "     continue;\n                    }\n                }\n            }\n        } else {\n         "
    "   action_id_t act = pick_action();\n            exec_action_by_id((uint8_t)act);\n        }\n\n    "
    "    log_remaining_time();\n\n        if ((xEventGroupGetBits(s_action_evt) & (STOP_BIT | DISCONNECT_"
    "BIT)) == 0) {\n            action_delay_ms(ACTION_GUARD_DELAY_MS);\n        }\n    }\n}\n\n#define R"
    "UNTIME_TICK_PERIOD_MS   60000\nstatic void runtime_tick_task(void *arg)\n{\n    (void)arg;\n    whil"
    "e (1) {\n        vTaskDelay(pdMS_TO_TICKS(RUNTIME_TICK_PERIOD_MS));\n\n        bool running = (s_act"
    "ion_evt != NULL) &&\n                      ((xEventGroupGetBits(s_action_evt) & RUN_BIT) != 0);\n\n "
    "       if (running) {\n             \n            if (s_run_deadline_us == 0 && s_sched_stop_deadlin"
    "e_us == 0) {\n                continue;\n            }\n            int64_t remain_us = get_remainin"
    "g_us();\n            if (remain_us <= 0) {\n                continue;\n            }\n            in"
    "t32_t remain_min = (int32_t)(remain_us / 1000000LL / 60);\n            int32_t remain_sec = (int32_t"
    ")((remain_us / 1000000LL) % 60);\n            ESP_LOGI(TAG, \"[wUwemZ] %ld c %ld B\",\n             "
    "        (long)remain_min, (long)remain_sec);\n            continue;\n        }\n\n        struct tm "
    "ti;\n        if (!wifi_manager_get_local_time(&ti)) {\n            continue;    \n        }\n       "
    " config_t *cfg = config_store_get();\n        if (cfg == NULL) {\n            continue;\n        }\n"
    "        int64_t now = esp_timer_get_time();\n        int64_t day_sec = (int64_t)ti.tm_hour * 3600 + "
    "ti.tm_min * 60 + ti.tm_sec;\n        int64_t day_us  = day_sec * 1000000LL;\n        int64_t start_u"
    "s = 0;    \n        for (uint8_t k = 0; k < cfg->timer_count && k < TIMER_RULE_MAX; k++) {\n        "
    "    timer_rule_t *sr = &cfg->timers[k];\n            if (!sr->enabled || sr->type != TIMER_START_STO"
    "P || sr->ss_action != 0) {\n                continue;\n            }\n            int64_t target_sec"
    " = (int64_t)sr->hour * 3600 + sr->minute * 60;\n            int64_t delta_us = (target_sec * 1000000"
    "LL) - day_us;\n            if (delta_us <= 0) {\n                delta_us += 24LL * 3600 * 1000000LL"
    ";    \n            }\n            int64_t ts = now + delta_us;\n            if (start_us == 0 || ts "
    "< start_us) {\n                start_us = ts;\n            }\n        }\n        if (start_us == 0) "
    "{\n            continue;    \n        }\n        int64_t remain_us = start_us - now;\n        if (re"
    "main_us <= 0) {\n            continue;\n        }\n        int32_t remain_min = (int32_t)(remain_us "
    "/ 1000000LL / 60);\n        int32_t remain_sec = (int32_t)((remain_us / 1000000LL) % 60);\n        E"
    "SP_LOGI(TAG, \"[cfZw\302\267jUTH] %ld r %ld K\",\n                 (long)remain_min, (long)remain_se"
    "c);\n    }\n}\n\nesp_err_t action_engine_start_task(void)\n{\n    if (s_task_created) {\n        ret"
    "urn ESP_OK;\n    }\n    s_action_evt = xEventGroupCreate();\n    if (s_action_evt == NULL) {\n      "
    "  ESP_LOGE(TAG, \"EventGroup wmBH\");\n        return ESP_ERR_NO_MEM;\n    }\n\n    s_led_evt = xEve"
    "ntGroupCreate();\n    if (s_led_evt == NULL) {\n        ESP_LOGE(TAG, \"LED EventGroup ukEl\");\n   "
    "     vEventGroupDelete(s_action_evt);\n        s_action_evt = NULL;\n        return ESP_ERR_NO_MEM;"
    "\n    }\n\n    BaseType_t ok = xTaskCreate(action_engine_task, \"action_engine\",\n                 "
    "               ACTION_TASK_STACK, NULL, ACTION_TASK_PRIORITY, NULL);\n    if (ok != pdPASS) {\n     "
    "   ESP_LOGE(TAG, \"BITXwevwDU\");\n        vEventGroupDelete(s_action_evt);\n        s_action_evt = "
    "NULL;\n        return ESP_FAIL;\n    }\n\n    BaseType_t ok2 = xTaskCreate(runtime_tick_task, \"runt"
    "ime_tick\",\n                                 ACTION_TASK_STACK, NULL,\n                            "
    "     ACTION_TASK_PRIORITY - 1, NULL);\n    if (ok2 != pdPASS) {\n        ESP_LOGW(TAG, \"vwrJHAxSagW"
    "kGu\357\274\210jERSvNZXW\357\274\211\");\n    }\n\n    BaseType_t ok3 = xTaskCreate(led_control_task"
    ", \"led_ctrl\",\n                                 ACTION_TASK_STACK, NULL,\n                        "
    "         ACTION_TASK_PRIORITY - 1, NULL);\n    if (ok3 != pdPASS) {\n        ESP_LOGW(TAG, \"LED pKl"
    "iouQm\357\274\210HHkZHaX\357\274\211\");\n    }\n\n    s_task_created = true;\n    ESP_LOGI(TAG, \"Z"
    "fvjfRIor\");\n    return ESP_OK;\n}\n\nvoid action_engine_start(void)\n{\n    if (s_action_evt == NU"
    "LL) {\n        return;\n    }\n     \n    if (s_run_deadline_us != 0) {\n        ESP_LOGI(TAG, \">>>"
    " KEY2 TPV\357\274\232wEDozbjrAuPfD\357\274\210yz\357\274\211<<<\");\n        reset_runtime();\n    }"
    " else {\n        ESP_LOGI(TAG, \">>> KEY2 Mrc\357\274\232HYgefG <<<\");\n    }\n\n    xEventGroupCle"
    "arBits(s_action_evt, STOP_BIT | DISCONNECT_BIT);\n    xEventGroupSetBits(s_action_evt, RUN_BIT);\n}"
    "\n\nvoid action_engine_stop(void)\n{\n    if (s_action_evt == NULL) {\n        return;\n    }\n     "
    "\n    xEventGroupClearBits(s_action_evt, RUN_BIT);\n    xEventGroupSetBits(s_action_evt, STOP_BIT);"
    "\n    reset_runtime();    \n    ESP_LOGI(TAG, \">>> KEY0 kts\357\274\232aBUfgu <<<\");\n\n    struct"
    " tm ti;\n    if (wifi_manager_get_local_time(&ti)) {\n        config_t *cfg = config_store_get();\n "
    "       if (cfg != NULL) {\n            int64_t now = esp_timer_get_time();\n            int64_t day_"
    "sec = (int64_t)ti.tm_hour * 3600 + ti.tm_min * 60 + ti.tm_sec;\n            int64_t day_us  = day_se"
    "c * 1000000LL;\n            int64_t start_us = 0;\n            for (uint8_t k = 0; k < cfg->timer_co"
    "unt && k < TIMER_RULE_MAX; k++) {\n                timer_rule_t *sr = &cfg->timers[k];\n            "
    "    if (!sr->enabled || sr->type != TIMER_START_STOP || sr->ss_action != 0) {\n                    c"
    "ontinue;\n                }\n                int64_t target_sec = (int64_t)sr->hour * 3600 + sr->min"
    "ute * 60;\n                int64_t delta_us = (target_sec * 1000000LL) - day_us;\n                if"
    " (delta_us <= 0) {\n                    delta_us += 24LL * 3600 * 1000000LL;\n                }\n   "
    "             int64_t ts = now + delta_us;\n                if (start_us == 0 || ts < start_us) {\n  "
    "                  start_us = ts;\n                }\n            }\n            if (start_us != 0) {"
    "\n                int64_t remain_us = start_us - now;\n                if (remain_us > 0) {\n       "
    "             int32_t remain_min = (int32_t)(remain_us / 1000000LL / 60);\n                    int32_"
    "t remain_sec = (int32_t)((remain_us / 1000000LL) % 60);\n                    ESP_LOGI(TAG, \"[WUgc] "
    "uKdwTADt %ld q %ld Q\",\n                             (long)remain_min, (long)remain_sec);\n        "
    "        }\n            }\n        }\n    }\n}\n\nbool action_engine_is_running(void)\n{\n    if (s_a"
    "ction_evt == NULL) {\n        return false;\n    }\n    return (xEventGroupGetBits(s_action_evt) & R"
    "UN_BIT) != 0;\n}\n\nbool action_engine_stop_and_wait(uint32_t timeout_ms)\n{\n    if (s_action_evt ="
    "= NULL) {\n        return true;\n    }\n    xEventGroupClearBits(s_action_evt, RUN_BIT);\n    xEvent"
    "GroupSetBits(s_action_evt, STOP_BIT);\n    reset_runtime();    \n\n    EventBits_t bits = xEventGrou"
    "pWaitBits(\n        s_action_evt, STOP_BIT, pdTRUE, pdFALSE, pdMS_TO_TICKS(timeout_ms));\n    return"
    " (bits & STOP_BIT) == 0;\n}\n\nvoid action_engine_stop_and_reset(void)\n{\n    if (s_action_evt == N"
    "ULL) {\n        return;\n    }\n\n    xEventGroupClearBits(s_action_evt, RUN_BIT);\n    xEventGroupS"
    "etBits(s_action_evt, STOP_BIT);\n    reset_runtime();    \n    ESP_LOGI(TAG, \">>> KEY3 bLg\357\274"
    "\232KPlUpVCmPuN <<<\");\n\n    xEventGroupWaitBits(\n        s_action_evt, STOP_BIT, pdTRUE, pdFALSE"
    ", pdMS_TO_TICKS(2000));\n\n    if (!ble_hid_is_connected()) {\n        ESP_LOGW(TAG, \"whJAI\357\274"
    "\214rBCORHio\357\274\214xECpzz\");\n        return;\n    }\n\n    if (!action_mouse_home()) {\n     "
    "   ESP_LOGW(TAG, \"qKWSLUT\357\274\210STOP/EV\357\274\211\");\n    } else {\n        ESP_LOGI(TAG, "
    "\"tPOzufBVHJ\357\274\214EOuSB\");\n    }\n}\n\nstatic void led_control_task(void *arg)\n{\n    (void"
    ")arg;\n    const action_timing_t *T = ae_timing();\n    bool running = false;\n    bool timed   = fa"
    "lse;        \n    int64_t remain_us = 0;\n    uint32_t freq_interval_ms = T->led_freq_per_1min_ms;\n"
    "\n    while (1) {\n        if (s_action_evt != NULL) {\n            running = (xEventGroupGetBits(s_"
    "action_evt) & RUN_BIT) != 0;\n        } else {\n            running = false;\n        }\n        rem"
    "ain_us = get_remaining_us();\n        timed = running && (remain_us > 0);\n\n        if (!running) {"
    "\n            led_status_set(false);                   \n             \n            EventBits_t b = "
    "xEventGroupWaitBits(s_led_evt, LED_BLINK_ONCE_BIT,\n                                                "
    "pdTRUE, pdFALSE, pdMS_TO_TICKS(200));\n            if (b & LED_BLINK_ONCE_BIT) {\n                xE"
    "ventGroupClearBits(s_led_evt, LED_BLINK_ONCE_BIT);\n                led_status_set(true);\n         "
    "       vTaskDelay(pdMS_TO_TICKS(T->led_blink_once_ms));\n                led_status_set(false);\n   "
    "             vTaskDelay(pdMS_TO_TICKS(T->led_blink_once_gap_ms));\n                led_status_set(tr"
    "ue);\n                vTaskDelay(pdMS_TO_TICKS(T->led_blink_once_ms));\n                led_status_s"
    "et(false);\n            }\n            continue;\n        }\n\n        if (!timed) {\n            le"
    "d_status_set(true);                    \n            xEventGroupWaitBits(s_led_evt, LED_BLINK_ONCE_B"
    "IT,\n                                pdTRUE, pdFALSE, pdMS_TO_TICKS(300));\n            if (xEventGr"
    "oupGetBits(s_led_evt) & LED_BLINK_ONCE_BIT) {\n                xEventGroupClearBits(s_led_evt, LED_B"
    "LINK_ONCE_BIT);\n                led_status_set(true);\n                vTaskDelay(pdMS_TO_TICKS(T->"
    "led_blink_once_ms));\n                led_status_set(false);\n                vTaskDelay(pdMS_TO_TIC"
    "KS(T->led_blink_once_gap_ms));\n                led_status_set(true);\n                vTaskDelay(pd"
    "MS_TO_TICKS(T->led_blink_once_ms));\n                led_status_set(false);\n            }\n        "
    "    continue;\n        }\n\n        int32_t remain_min = (int32_t)(remain_us / 1000000LL / 60);\n   "
    "     freq_interval_ms = (uint32_t)remain_min * T->led_freq_per_1min_ms;   \n        if (freq_interva"
    "l_ms < T->led_freq_per_1min_ms) {\n            freq_interval_ms = T->led_freq_per_1min_ms;    \n    "
    "    }\n        if (freq_interval_ms > T->led_freq_max_ms) {\n            freq_interval_ms = T->led_f"
    "req_max_ms;         \n        }\n\n        led_status_set(true);                        \n        vT"
    "askDelay(pdMS_TO_TICKS(T->led_blink_on_ms));\n        led_status_set(false);                       "
    "\n\n        EventBits_t b = xEventGroupWaitBits(s_led_evt, LED_BLINK_ONCE_BIT,\n                    "
    "                        pdTRUE, pdFALSE,\n                                            pdMS_TO_TICKS("
    "freq_interval_ms));\n        if (b & LED_BLINK_ONCE_BIT) {\n            xEventGroupClearBits(s_led_e"
    "vt, LED_BLINK_ONCE_BIT);\n            led_status_set(true);\n            vTaskDelay(pdMS_TO_TICKS(T-"
    ">led_blink_once_ms));\n            led_status_set(false);\n            vTaskDelay(pdMS_TO_TICKS(T->l"
    "ed_blink_once_gap_ms));\n            led_status_set(true);\n            vTaskDelay(pdMS_TO_TICKS(T->"
    "led_blink_once_ms));\n            led_status_set(false);\n        }\n    }\n}\n\nvoid action_engine_"
    "add_runtime(void)\n{\n    if (s_action_evt == NULL) {\n        return;\n    }\n\n    int64_t now = e"
    "sp_timer_get_time();\n\n    s_runtime_minutes += KEY1_ADD_MINUTES;\n    if (s_run_deadline_us != 0 &"
    "& s_run_deadline_us > now) {\n        s_run_deadline_us += (int64_t)KEY1_ADD_MINUTES * 60 * 1000000L"
    "L;\n    } else {\n        s_run_deadline_us = now + (int64_t)KEY1_ADD_MINUTES * 60 * 1000000LL;\n   "
    " }\n\n    if ((xEventGroupGetBits(s_action_evt) & RUN_BIT) == 0) {\n        xEventGroupClearBits(s_a"
    "ction_evt, STOP_BIT | DISCONNECT_BIT);\n        xEventGroupSetBits(s_action_evt, RUN_BIT);\n    }\n"
    "\n    ESP_LOGI(TAG, \">>> KEY1 ibV\357\274\232EIwY +%d cM\357\274\210fQ %ld XF\357\274\211<<<\",\n  "
    "           KEY1_ADD_MINUTES, (long)s_runtime_minutes);\n\n    led_notify_blink_once();\n}\n\nvoid ac"
    "tion_engine_apply_config(const config_t *cfg)\n{\n    if (cfg == NULL) {\n        return;\n    }\n  "
    "  s_run_mode = cfg->run_mode;\n    s_weights  = cfg->weights;\n    memcpy(&s_sequence, &cfg->sequenc"
    "e, sizeof(s_sequence));\n    s_seq_cursor = 0;\n    s_seq_shuffle_len = 0;\n    s_seq_once_stop = fa"
    "lse;\n    if (s_sequence.cycle == CYCLE_SHUFFLE && s_sequence.count > 0) {\n        build_shuffle_or"
    "der(&s_sequence);\n    }\n    ESP_LOGI(TAG, \"RfgB\357\274\232mode=%d seq_count=%d\", s_run_mode, s_"
    "sequence.count);\n}\n\nvoid action_engine_set_mode(run_mode_t mode)\n{\n    s_run_mode = (mode == RU"
    "N_MODE_SEQUENCE) ? RUN_MODE_SEQUENCE : RUN_MODE_RANDOM;\n    s_seq_cursor = 0;\n    s_seq_shuffle_le"
    "n = 0;\n    s_seq_once_stop = false;\n    ESP_LOGI(TAG, \"bIvMlrx %d\", s_run_mode);\n}\n\nvoid acti"
    "on_engine_set_weights(const action_weights_t *w)\n{\n    if (w == NULL) {\n        return;\n    }\n "
    "   s_weights = *w;\n    ESP_LOGI(TAG, \"ZJQk\357\274\232drag=%d click=%d wheel=%d arrow=%d rest=%d m"
    "ove=%d word=%d\",\n             s_weights.drag, s_weights.click, s_weights.wheel,\n             s_we"
    "ights.arrow, s_weights.rest, s_weights.move, s_weights.word);\n}\n\nvoid action_engine_set_sequence("
    "const action_seq_t *seq)\n{\n    if (seq == NULL) {\n        return;\n    }\n    memcpy(&s_sequence,"
    " seq, sizeof(s_sequence));\n    s_seq_cursor = 0;\n    s_seq_shuffle_len = 0;\n    s_seq_once_stop ="
    " false;\n    if (s_sequence.cycle == CYCLE_SHUFFLE && s_sequence.count > 0) {\n        build_shuffle"
    "_order(&s_sequence);\n    }\n    ESP_LOGI(TAG, \"xwQb\357\274\232count=%d cycle=%d\", s_sequence.cou"
    "nt, s_sequence.cycle);\n}\n\n#define SCHED_TICK_MS       1000\n#define SCHED_STACK         3072\n#de"
    "fine SCHED_PRIORITY      (ACTION_TASK_PRIORITY - 2)\n\nstatic int64_t s_last_fire_min[TIMER_RULE_MAX"
    "];\nstatic int64_t s_boot_ms = 0;\n\nstatic int64_t now_ms_since_boot(void)\n{\n    return (int64_t)"
    "(esp_timer_get_time() / 1000LL);\n}\n\nstatic void scheduler_task(void *arg)\n{\n    (void)arg;\n   "
    " s_boot_ms = now_ms_since_boot();\n    for (int i = 0; i < TIMER_RULE_MAX; i++) {\n        s_last_fi"
    "re_min[i] = -1;\n    }\n\n    while (1) {\n        vTaskDelay(pdMS_TO_TICKS(SCHED_TICK_MS));\n\n    "
    "    config_t *cfg = config_store_get();\n        if (cfg == NULL) {\n            continue;\n        "
    "}\n        int64_t elapsed_min = (now_ms_since_boot() - s_boot_ms) / 60000LL;\n\n        struct tm t"
    "i;\n        bool have_time = wifi_manager_get_local_time(&ti);\n        int cur_min_of_day = have_ti"
    "me ? (ti.tm_hour * 60 + ti.tm_min) : -1;\n\n        bool synced_now = wifi_manager_time_synced();\n "
    "       if (synced_now && !s_prev_synced) {\n            s_timeset_guard_until = esp_timer_get_time()"
    " + (int64_t)TIMESET_GUARD_US;\n            ESP_LOGI(TAG, \"xBpilm\357\274\214qd %d CwjofTnvQ\",\n   "
    "                  (int)(TIMESET_GUARD_US / 1000000));\n        }\n        s_prev_synced = synced_now"
    ";\n        if (synced_now && s_timeset_guard_until != 0 &&\n            esp_timer_get_time() < s_tim"
    "eset_guard_until) {\n            continue;    \n        }\n\n        int64_t sched_stop_us = 0;\n   "
    "     if (have_time) {\n            int64_t now = esp_timer_get_time();\n             \n            i"
    "nt64_t day_sec = (int64_t)ti.tm_hour * 3600 + ti.tm_min * 60 + ti.tm_sec;\n            int64_t day_u"
    "s  = day_sec * 1000000LL;\n            for (uint8_t k = 0; k < cfg->timer_count && k < TIMER_RULE_MA"
    "X; k++) {\n                timer_rule_t *sr = &cfg->timers[k];\n                if (!sr->enabled || "
    "sr->type != TIMER_START_STOP || sr->ss_action != 1) {\n                    continue;\n              "
    "  }\n                int64_t target_sec = (int64_t)sr->hour * 3600 + sr->minute * 60;\n             "
    "   int64_t delta_us = (target_sec * 1000000LL) - day_us;\n                if (delta_us <= 0) {\n    "
    "                delta_us += 24LL * 3600 * 1000000LL;    \n                }\n                int64_t"
    " ts = now + delta_us;\n                if (sched_stop_us == 0 || ts < sched_stop_us) {\n            "
    "        sched_stop_us = ts;\n                }\n            }\n        }\n        s_sched_stop_deadl"
    "ine_us = sched_stop_us;\n\n        for (uint8_t i = 0; i < cfg->timer_count && i < TIMER_RULE_MAX; i"
    "++) {\n            timer_rule_t *r = &cfg->timers[i];\n            if (!r->enabled) {\n             "
    "   continue;\n            }\n            if (r->type == TIMER_START_STOP) {\n                if (!ha"
    "ve_time) {\n                    continue;\n                }\n                 \n                if "
    "(s_last_fire_min[i] == elapsed_min && elapsed_min >= 0) {\n                    continue;\n          "
    "      }\n                if (cur_min_of_day == (r->hour * 60 + r->minute)) {\n                    s_"
    "last_fire_min[i] = elapsed_min;\n                     \n                    if (r->ss_action == 0) {"
    "\n                        ESP_LOGI(TAG, \"[oRct] oa%d mdgQ\", i);\n                        action_en"
    "gine_start();\n                    } else {\n                        ESP_LOGI(TAG, \"[yihc] sV%d Mso"
    "l\", i);\n                        s_sched_stop_deadline_us = 0;    \n                        action_"
    "engine_stop();\n                    }\n                }\n            } else if (r->type == TIMER_SI"
    "NGLE_ACTION) {\n                if (!have_time) {\n                    continue;\n                }"
    "\n                if (s_last_fire_min[i] == elapsed_min && elapsed_min >= 0) {\n                    "
    "continue;\n                }\n                if (cur_min_of_day == (r->hour * 60 + r->minute)) {\n "
    "                   s_last_fire_min[i] = elapsed_min;\n                    ESP_LOGI(TAG, \"[OmKGt] dy"
    "%d Wz\", i);\n                    action_engine_run_single(r->action_id);\n                }\n      "
    "      } else if (r->type == TIMER_PERIODIC) {\n                 \n                if (!have_time) {"
    "\n                    continue;\n                }\n                if (r->period_min == 0) {\n     "
    "               continue;\n                }\n                if (elapsed_min >= 0 && (elapsed_min % "
    "(int64_t)r->period_min) == 0\n                    && s_last_fire_min[i] != elapsed_min) {\n         "
    "           s_last_fire_min[i] = elapsed_min;\n                    ESP_LOGI(TAG, \"[uYDC] RQ%d vqCQ(h"
    "%dM)\", i, r->period_min);\n                    action_engine_trigger_sequence_once();\n            "
    "    }\n            }\n        }\n    }\n}\n\nesp_err_t action_engine_start_scheduler(void)\n{\n    B"
    "aseType_t ok = xTaskCreate(scheduler_task, \"km_sched\", SCHED_STACK, NULL,\n                       "
    "         SCHED_PRIORITY, NULL);\n    if (ok != pdPASS) {\n        ESP_LOGE(TAG, \"PvciAggqPy\");\n  "
    "      return ESP_FAIL;\n    }\n    ESP_LOGI(TAG, \"JwTZGxdKg\");\n    return ESP_OK;\n}\n"
    ;
